import Head from 'next/head'
// import Image from 'next/image'
import Button from '../components/Button'
import styles from '../styles/Home.module.css'
import Logo from '../components/Logo'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Equalizer landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"></link>
      </Head>

      <body>

        <main className={styles.container}>


          <div className={styles.prebody}>
            <Logo />
            <h2>We make your music sound extraordinary.</h2>
            <div className="body2">A system audio equalizer specifically designed for Android and iOS. Freely tune the
              way your music sounds with a professional grade parametric EQ & volume mixer. Control
              bass, mids, treble, gain control, reverb, and more!</div>
          </div>

          <div className={styles.mainbody}>
            <div className={styles.layer1}>
              <img
                src='illustration-app.png'
                alt='phone'
              />
            </div>

            <div className={styles.layer2}>
            </div>
            <div className={styles.layer3}>
              <div className={`${styles["layer3-content"]}`}>

                <h3>Premium EQ</h3>

                <p>
                  Get expert-level control with a robust equalizer, volume mixer, and spatial audio. Take
                  your listening experience to a whole new level and access all our incredible features!
                </p>
                <div className={styles.price}>
                  <span className={styles.dollar}>$4</span><span> / month</span>
                </div>

                <div className={styles.buttons}>
                <Button
                  type='ios_button'
                  text='iOS Download'
                  icon='icon-apple.svg'
                />
                </div>

                <div className={styles.buttons}>
                <Button
                  type='android_button'
                  text='Android Download'
                  icon='icon-android.svg'
                /> 
                </div>
              </div>
            </div>

          </div>

          <div className={styles.postbody}>
            <Logo />

            <p>All rights reserved © Equalizer 2021<br />
              Have any problems? Contact us via social media or email us at <strong>equalizer@example.com</strong></p>

            <Footer />
          </div>

        </main>

      </body>

    </>
  )
}


{/* <br />
          <br />
          <Button
            type='ios_button'
            text='iOS Download'
            icon='icon-apple.svg'
          />
          <br />
          <br />
          <Button
            type='android_button'
            text='Android Download'
            icon='icon-android.svg'
          />
          <br />
          <br /> */}